#python train.py --log_name bert_project_f30k_1 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path D:\study\study_dataset\vse_infty-master\data
#python train.py --log_name bert_project_f30k_18 --data_name flickr30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path C:/datasets/data
##python train.py --log_name bert_project_f30k_4 --data_name flickr30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path D:/study/study_dataset/vse_infty-master/data
#
#
#
#
#python train.py --log_name bert_project_f30k_11 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  D:/study/study_dataset/vse_infty-master/data --lr_update 15
#python train.py --log_name bert_project_f30k_12 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  D:/study/study_dataset/vse_infty-master/data --lr_update 15
#python train.py --log_name bert_project_f30k_1 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  C:/datasets/data --lr_update 15
#python train.py --log_name bert_project_f30k_16 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  C:/datasets/data --lr_update 15
#python train.py --log_name bert_project_f30k_17 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  C:/datasets/data --lr_update 15

#python train.py --log_name bert_project_f30k_14 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  D:/study/study_dataset/vse_infty-master/data --lr_update 15
#python train.py --log_name bert_project_f30k_5 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  D:/study/study_dataset/vse_infty-master/data --lr_update 15
#python train.py --log_name bert_project_f30k_0 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  D:/study/study_dataset/vse_infty-master/data --lr_update 15
#python train.py --log_name bert_project_f30k_1 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  D:/study/study_dataset/vse_infty-master/data --lr_update 15
#python train.py --log_name bert_project_f30k_2 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  D:/study/study_dataset/vse_infty-master/data --lr_update 15
python train.py --log_name bert_project_f30k_8 --data_name f30k    --precomp_enc_type basic     --batch_size 128      --txt_enc_type bert         --bert_type ./bert-base-uncased       --img_enc_type project        --loss_type acc            --data_path  D:/study/study_dataset/vse_infty-master/data --lr_update 15